#!/bin/bash

# Blender déjà installé et dans le PATH via Dockerfile

# Lancer ton script en arrière-plan
cd ${HOME}/program
python main.py &

# Lancer Jupyter
exec jupyter notebook --no-browser --ip 0.0.0.0 --port 8888
