#!/bin/bash

# Blender déjà installé et dans le PATH via Dockerfile

# Lancer ton script en arrière-plan
cd ${HOME}/programs
python main.py &

# Lancer Jupyter (requis par MyBinder pour rester actif)
exec "$@"
